export const QUERY_KEYS = {
  dashboard:              ['dashboard'] as const,
  dashboardOpportunities: ['dashboard', 'opportunities'] as const,
  accounts:    (f: unknown) => ['accounts', f] as const,
  account:     (id: number) => ['accounts', id] as const,
  accountProducts: (id: number) => ['accounts', id, 'products'] as const,
  accountTickets:  (id: number) => ['accounts', id, 'tickets'] as const,
  accountHealth:   (id: number) => ['accounts', id, 'health'] as const,
  accountHealthHistory: (id: number) => ['accounts', id, 'health', 'history'] as const,
  accountVisits:   (id: number) => ['accounts', id, 'visits'] as const,
  accountReleases: (id: number) => ['accounts', id, 'release-matches'] as const,
  tickets:   (f: unknown) => ['tickets', f] as const,
  renewals:  (f: unknown) => ['renewals', f] as const,
  releases:  (f: unknown) => ['releases', f] as const,
  releaseMatches: (id: number) => ['releases', id, 'matches'] as const,
  agentRun:  (runId: number) => ['agent', 'run', runId] as const,
  agentLatest: (accountId: number, type: string) => ['agent', accountId, type] as const,
  users:     (f: unknown) => ['users', f] as const,
  zones:     ['zones'] as const,
  siPartners: ['si-partners'] as const,
  products:  (f: unknown) => ['products', f] as const,
};
